version: "3.7"
services:
  db:
   image: postgres:16-alpine
   restart: always
   env_file: .env
   environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGDATA: ${POSTGRES_DATA}
      DATABASE_URL: ${DATABASE_URL}
   ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
   expose:
      - "${POSTGRES_PORT}"
   volumes:
      - postgres-data:${POSTGRES_DATA}

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379

  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    env_file: .env
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    depends_on:
      - app
volumes:
  postgres-data:
